[package]
name = "aldrin-parser"
description = "Aldrin schema parser library"
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
heck = "0.3.1"
pest = "2.1.3"
pest_derive = "2.1.0"
strsim = "0.10.0"
unicode-segmentation = "1.6.0"
unicode-width = "0.1.8"
uuid = { version = "0.8.1", features = ["v4"] }
