[package]
name = "chat"
version = "0.0.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
aldrin-broker = { path = "../../../rust/broker" }
aldrin-client = { path = "../../../rust/client", features = ["codegen"] }
aldrin-codec = { path = "../../../rust/codec", features = ["json-serializer", "tokio-io"] }
anyhow = "1.0.32"
clap = { version = "3.0.0-beta.1", features = ["wrap_help"] }
crossterm = "0.16.0"
futures = { version = "0.3.4", default-features = false, features = ["std"] }
linefeed = "0.6.0"
tokio = { version = "0.2.11", default-features = false, features = ["rt-threaded", "macros", "tcp"] }
uuid = { version = "0.8.1", default-features = false, features = ["v4"] }
