[package]
name = "conformance-test-broker"
description = "Host for aldrin-broker conformance tests"
version = "0.0.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.64.0"
publish = false

[dependencies]
anyhow = "1.0.32"
serde_json = "1.0.48"

[dependencies.aldrin-broker]
version = "0.1.0"
path = "../broker"

[dependencies.aldrin-codec]
version = "0.1.0"
path = "../codec"
features = [
    "json-serializer",
    "tokio-codec",
]

[dependencies.aldrin-conformance-test-shared]
version = "0.1.0"
path = "../../conformance-test-shared"

[dependencies.futures]
version = "0.3.21"
default-features = false

[dependencies.tokio]
version = "1.0.0"
features = [
    "io-std",
    "macros",
    "net",
    "rt-multi-thread",
]

[dependencies.tokio-util]
version = "0.7.1"
features = ["codec"]
