[package]
name = "hello-world"
version = "0.0.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
aldrin-broker = { path = "../../../rust/broker" }
aldrin-channel = { path = "../../../rust/channel" }
aldrin-client = { path = "../../../rust/client" }
anyhow = "1.0.32"
futures = { version = "0.3.4", default-features = false }
tokio = { version = "0.3.3", default-features = false, features = ["macros", "rt-multi-thread"] }
