[package]
name = "ping"
version = "0.0.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
aldrin-broker = { path = "../../../rust/broker" }
aldrin-client = { path = "../../../rust/client", features = ["codegen"] }
aldrin-codec = { path = "../../../rust/codec", features = ["json-serializer", "tokio-codec"] }
anyhow = "1.0.32"
clap = { version = "3.0.0-beta.2", features = ["wrap_help"] }
futures = { version = "0.3.4", default-features = false, features = ["std"] }
tokio = { version = "1.0.0", default-features = false, features = ["macros", "net", "rt-multi-thread", "time"] }
