[package]
name = "aldrin-codegen-macros"
description = "Aldrin code generator macros"
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.65.0"

[lib]
proc-macro = true

[dependencies.aldrin-codegen]
version = "0.1.0"
path = "../codegen"
default-features = false
features = ["rust"]

[dependencies.aldrin-parser]
version = "0.1.0"
path = "../parser"
default-features = false

[dependencies.proc-macro-error]
version = "1.0.3"
default-features = false

[dependencies.proc-macro2]
version = "1.0.18"
default-features = false

[dependencies.syn]
version = "1.0.14"
default-features = false
features = [
    "parsing",
    "printing",
    "proc-macro",
]

[dev-dependencies.aldrin-client]
version = "0.1.0"
path = "../../client"
features = ["codegen"]
