[package]
name = "aldrin-codegen-macros"
description = "Aldrin code generator macros"
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
aldrin-codegen = { version = "0.1.0", path = "../codegen", features = ["rust"] }
aldrin-parser = { version = "0.1.0", path = "../parser" }
syn = "1.0.14"
