[package]
name = "aldrin-codegen-macros"
description = "Aldrin code generator macros"
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.64.0"

[lib]
proc-macro = true

[dependencies]
aldrin-codegen = { version = "0.1.0", path = "../codegen", features = ["rust"] }
aldrin-parser = { version = "0.1.0", path = "../parser" }
proc-macro-error = "1.0.3"
proc-macro2 = "1.0.18"
syn = "1.0.14"

[dev-dependencies]
aldrin-client = { version = "0.1.0", path = "../client" }
