[package]
name = "aldrin-codegen"
description = "Aldrin code generator library"
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.65.0"

[features]
default = ["rust"]
rust = []

[dependencies.aldrin-parser]
version = "0.1.0"
path = "../parser"
default-features = false

[dependencies.diffy]
version = "0.3.0"
default-features = false

[dependencies.heck]
version = "0.4.0"
default-features = false

[dev-dependencies]
uuid = "1.1.2"

[dev-dependencies.aldrin-client]
version = "0.1.0"
path = "../client"
features = ["codegen"]

[dev-dependencies.aldrin-proto]
version = "0.1.0"
path = "../proto"

[dev-dependencies.aldrin-test]
version = "0.1.0"
path = "../test"
features = ["tokio"]

[dev-dependencies.futures]
version = "0.3.21"
default-features = false

[dev-dependencies.tokio]
version = "1.0.0"
features = [
    "macros",
    "rt",
]
