[package]
name = "aldrin-codegen"
description = "Aldrin code generator library"
version = "0.1.0"
authors = ["Dennis Hamester <dennis.hamester@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
heck = "0.3.1"
pest = "2.1.2"
pest_derive = "2.1.0"
semver = "0.9.0"
uuid = "0.8.1"
