[package]
name = "aldrin-codegen"
description = "Aldrin code generator library"
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2018"

[features]
default = ["rust"]
rust = []

[dependencies]
aldrin-parser = { version = "0.1.0", path = "../parser" }
heck = "0.3.1"
