[package]
name = "aldrin-codegen"
description = "Aldrin code generator library"
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2018"

[features]
default = ["rust"]
rust = []

[dependencies]
aldrin-parser = { version = "0.1.0", path = "../parser" }
diffy = "0.2.0"
heck = "0.3.1"

[dev-dependencies]
aldrin-client = { version = "0.1.0", path = "../client", features = ["codegen"] }
aldrin-proto = { version = "0.1.0", path = "../proto" }
aldrin-test = { version = "0.1.0", path = "../test", features = ["tokio"] }
futures = { version = "0.3.4", default-features = false }
tokio = { version = "0.2.11", features = ["macros", "rt-core"] }
