[package]
name = "aldrin-broker"
description = "Broker library of Aldrin, a lightweight and composable RPC framework."
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
aldrin-proto = { version = "0.1.0", path = "../proto" }
futures-channel = { version = "0.3.4", default-features = false, features = ["std"] }
futures-core = { version = "0.3.4", default-features = false }
futures-util = { version = "0.3.4", default-features = false }
uuid = { version = "0.8.1", default-features = false, features = ["v4"] }

[dev-dependencies]
aldrin-client = { version = "0.1.0", path = "../client" }
aldrin-util = { version = "0.1.0", path = "../util", features = ["channel"] }
tokio = { version = "0.2.11", features = ["macros", "rt-core", "time"] }
