[package]
name = "example-introspect"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.75"
uuid = "1.6.1"

[dependencies.aldrin]
path = "../../aldrin"
features = [
    "introspection",
    "tokio",
]

[dependencies.clap]
version = "4.4.8"
features = ["derive"]

[dependencies.tokio]
version = "1.34.0"
features = [
    "macros",
    "net",
    "rt-multi-thread",
]
