[package]
name = "example-broker"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.75"
env_logger = "0.10.1"
log = "0.4.20"

[dependencies.aldrin-broker]
path = "../../broker"
features = ["tokio"]

[dependencies.clap]
version = "4.4.8"
features = ["derive"]

[dependencies.tokio]
version = "1.34.0"
features = [
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
]
