[package]
name = "aldrin-proto"
description = "Protocol definitions of Aldrin, a lightweight and composable RPC framework."
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.64.0"

[features]
new-v4-ids = ["uuid/v4"]
serde = [
    "dep:serde",
    "uuid/serde",
]

[dependencies.pin-project]
version = "1.0.10"
default-features = false

[dependencies.serde]
optional = true
version = "1.0.104"
default-features = false
features = [
    "derive",
    "std",
]

[dependencies.uuid]
version = "1.1.2"
default-features = false
