[package]
name = "aldrin-util"
description = "Additional utilities for working with Aldrin."
version = "0.1.0"
authors = ["Dennis Hamester <dennis.hamester@gmail.com>"]
license = "MIT"
edition = "2018"

[features]
channel = [ "futures-channel/std", "futures-channel/sink", "futures-core", "futures-sink" ]

[dependencies]
aldrin-proto = { version = "0.1.0", path = "../proto" }

futures-channel = { optional = true, version = "0.3.1", default-features = false }
futures-core = { optional = true, version = "0.3.1", default-features = false }
futures-sink = { optional = true, version = "0.3.1", default-features = false }
