[package]
name = "aldrin-util"
description = "Additional utilities for working with Aldrin."
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2018"
autobenches = false

[features]
bincode-serializer = ["aldrin-proto/serde-derive", "bincode", "codec"]
codec = ["bytes"]
json = ["aldrin-proto/serde-derive", "codec", "serde_json"]
tokio-io = ["codec", "pin-project", "tokio"]

[dependencies]
aldrin-proto = { version = "0.1.0", path = "../proto" }

bincode = { optional = true, version = "1.3.1" }
bytes = { optional = true, version = "0.5.4" }
pin-project = { optional = true, version = "0.4.8" }
serde_json = { optional = true, version = "1.0.48" }
tokio = { optional = true, version = "0.2.11" }

[dev-dependencies]
aldrin-proto = { version = "0.1.0", path = "../proto", features = ["serde-derive"] }
criterion = "0.3.3"
maplit = "1.0.2"
serde_json = "1.0.48"
uuid = "0.8.1"

[[bench]]
name = "benches"
harness = false
