[package]
name = "aldrin-codec"
description = "Encoder/decoder-based Aldrin transports"
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.64.0"
autobenches = false

[features]
bincode-serializer = [
    "aldrin-proto/serde",
    "bincode",
]
json-serializer = [
    "aldrin-proto/serde",
    "serde_json",
]
tokio-codec = [
    "pin-project",
    "tokio",
]

[dependencies.aldrin-proto]
version = "0.1.0"
path = "../proto"
default-features = false

[dependencies.bincode]
optional = true
version = "1.3.1"
default-features = false

[dependencies.bytes]
version = "1.2.0"
default-features = false
features = ["std"]

[dependencies.pin-project]
optional = true
version = "1.0.10"
default-features = false

[dependencies.serde_json]
optional = true
version = "1.0.48"
default-features = false
features = ["std"]

[dependencies.tokio]
optional = true
version = "1.0.0"
default-features = false

[dev-dependencies]
criterion = "0.4.0"
maplit = "1.0.2"
serde_json = "1.0.48"
uuid = "1.1.2"

[[bench]]
name = "benches"
harness = false
