[package]
name = "aldrin-codec"
description = "Encoder/decoder-based Aldrin transports"
version = "0.1.0"
authors = ["Aldrin Contributors"]
license = "Apache-2.0"
edition = "2018"
autobenches = false

[features]
bincode-serializer = ["aldrin-proto/serde-derive", "bincode"]
json-serializer = ["aldrin-proto/serde-derive", "serde_json"]
tokio-codec = ["pin-project", "tokio"]

[dependencies]
aldrin-proto = { version = "0.1.0", path = "../proto" }
bytes = "0.6.0"

bincode = { optional = true, version = "1.3.1" }
pin-project = { optional = true, version = "1.0.1" }
serde_json = { optional = true, version = "1.0.48" }
tokio = { optional = true, version = "0.3.3" }

[dev-dependencies]
aldrin-proto = { version = "0.1.0", path = "../proto", features = ["serde-derive"] }
criterion = "0.3.3"
maplit = "1.0.2"
serde_json = "1.0.48"
uuid = "0.8.1"

[[bench]]
name = "benches"
harness = false
