[package]
name = "aldrin-macros"
description = "Aldrin code generation macros."
version = "0.2.0"
authors = ["Aldrin Contributors"]
repository = "https://github.com/dennis-hamester/aldrin"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.70.0"
categories = [
    "asynchronous",
    "network-programming",
]
keywords = [
    "async",
    "network",
    "rpc",
    "service",
]

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
all-features = true

[lib]
proc-macro = true

[dependencies.aldrin-codegen]
version = "0.2.0"
path = "../codegen"
default-features = false
features = ["rust"]

[dependencies.aldrin-parser]
version = "0.2.0"
path = "../parser"
default-features = false

[dependencies.proc-macro-error]
version = "1.0.4"
default-features = false

[dependencies.proc-macro2]
version = "1.0.69"
default-features = false

[dependencies.syn]
version = "2.0.39"
default-features = false
features = [
    "parsing",
    "printing",
    "proc-macro",
]

[dev-dependencies.aldrin]
path = "../aldrin"
features = ["codegen"]
