[package]
name = "aldrin-broker"
description = """
Broker library of Aldrin, a message bus for service-oriented RPC and interprocess communication.
"""
version = "0.2.0"
authors = ["Aldrin Contributors"]
repository = "https://github.com/dennis-hamester/aldrin"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.70.0"
categories = [
    "asynchronous",
    "network-programming",
]
keywords = [
    "async",
    "network",
    "rpc",
    "service",
]

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
all-features = true

[features]
channel = ["aldrin-core/channel"]
statistics = []
tokio = ["aldrin-core/tokio"]

[dependencies.aldrin-core]
version = "0.2.0"
path = "../core"
default-features = false
features = ["new-v4-ids"]

[dependencies.futures-channel]
version = "0.3.29"
default-features = false
features = [
    "sink",
    "std",
]

[dependencies.futures-core]
version = "0.3.29"
default-features = false

[dependencies.futures-util]
version = "0.3.29"
default-features = false
features = ["sink"]

[dev-dependencies]
anyhow = "1.0.75"

[dev-dependencies.aldrin]
path = "../aldrin"

[dev-dependencies.aldrin-core]
path = "../core"
features = [
    "channel",
    "tokio",
]

[dev-dependencies.aldrin-test]
path = "../test"
features = ["tokio"]

[dev-dependencies.tokio]
version = "1.34.0"
features = [
    "macros",
    "net",
    "rt-multi-thread",
    "time",
]
