[package]
name = "aldrin-transport"
description = "Transport trait definition of Aldrin, a lightweight and composable RPC framework."
version = "0.1.0"
authors = ["Dennis Hamester <dennis.hamester@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
aldrin-proto = { version = "0.1.0", path = "../proto" }
futures-core = { version = "0.3.1", default-features = false }
futures-sink = { version = "0.3.1", default-features = false }
