[package]
name = "aldrin-parser2"
description = "Aldrin schema parser library."
version = "0.13.0"

categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true

[package.metadata.playground]
all-features = true

[dependencies]
annotate-snippets = { workspace = true }

[dependencies.bitflags]
version = "2.13.0"
default-features = false

[dependencies.chumsky]
version = "0.13.0"
default-features = false

[dependencies.derive_more]
version = "2.1.1"
default-features = false
features = [
    "debug",
    "from",
]

[dependencies.indexmap]
version = "2.14.0"
default-features = false
features = ["std"]

[dependencies.logos]
version = "0.16.1"
default-features = false
features = ["export_derive"]
