name: CI

on:
  push:
    branches-ignore:
    - 'wip/**'

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:

  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.70.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo check
        run: cargo check --locked --all-features --tests
      - name: Cargo test
        run: cargo test --locked --all-features
      - name: Cargo clippy
        if: ${{ matrix.rust == 'stable' }}
        run: cargo clippy --locked --all-features --tests

  doc:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo doc
        run: cargo doc --locked --all-features --no-deps

  style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Cargo fmt
        run: cargo fmt -- --check

  conformance:
    name: Protocol conformance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build aldrin-conformance-tester
        run: cargo build --locked -p aldrin-conformance-tester
      - name: Build conformance-test-broker
        run: cargo build --locked -p conformance-test-broker
      - name: Run conformance tests
        run: target/debug/aldrin-conformance-tester run -j1 target/debug/conformance-test-broker
