name: Rust Examples

on:
  push:
    branches-ignore:
    - 'wip/**'
    paths:
    - '.github/workflows/**'
    - 'examples/rust/**'
    - 'examples/schemas/**'
    - 'rust/**'

jobs:

  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.43.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: clippy
          default: true
      - name: Rust version
        run: rustc --version --verbose
      - name: Cargo version
        run: cargo --version --verbose
      - name: Cargo clippy
        working-directory: examples/rust
        run: cargo clippy --all-features

  style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          default: true
      - name: Cargo fmt
        working-directory: examples/rust
        run: cargo fmt -- --check
