name: Rust

on:
  push:
    branches-ignore:
    - 'wip/**'
    paths:
    - '.github/workflows/rust.yaml'
    - 'Cargo.lock'
    - 'Cargo.toml'
    - 'conformance-tester-shared/**'
    - 'conformance-tester/**'
    - 'gen/**'
    - 'rust/**'

jobs:

  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.54.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: clippy
          default: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo check
        run: cargo check --locked --all-features --tests --benches
      - name: Cargo test
        run: cargo test --locked --all-features
      - name: Cargo clippy
        run: cargo clippy --locked --all-features --tests --benches

  doc:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Cargo doc
        run: cargo doc --locked --all-features --no-deps

  style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          default: true
      - name: Cargo fmt
        run: cargo fmt -- --check

  conformance:
    name: Protocol conformance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build aldrin-conformance-tester
        run: cargo build --locked -p aldrin-conformance-tester
      - name: Build conformance-test-client
        run: cargo build --locked -p conformance-test-client
      - name: Run client tests
        run: target/debug/aldrin-conformance-tester client run -j1 target/debug/conformance-test-client
      - name: Build conformance-test-broker
        run: cargo build --locked -p conformance-test-broker
      - name: Run broker tests
        run: target/debug/aldrin-conformance-tester broker run -j1 target/debug/conformance-test-broker
