name: Rust

on:
  push:
    branches-ignore:
    - 'wip/**'
    paths:
    - '.github/workflows/**'
    - 'gen/**'
    - 'rust/**'

jobs:

  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly
          - 1.43.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: clippy
          default: true
      - name: Rust version
        run: rustc --version --verbose
      - name: Cargo version
        run: cargo --version --verbose
      - name: Cargo check
        run: cargo check --all-features --tests --benches
      - name: Cargo test
        run: cargo test --all-features
      - name: Cargo clippy
        run: |
          cargo clean
          cargo clippy --all-features

  doc:
    name: Check docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          default: true
      - name: Rust version
        run: rustc --version --verbose
      - name: Cargo version
        run: cargo --version --verbose
      - name: Cargo doc
        run: cargo doc --all-features --no-deps

  style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt
          default: true
      - name: Cargo fmt
        run: cargo fmt -- --check
